import { pt } from 'lively.graphics';
export const CONSTANTS = {
  LABEL_X: 10,
  WIDGET_X: 65,
  WIDGET_Y: 0,
  KEYFRAME_BUTTON_X: 100,
  TARGET_PICKER_DIAMETER: 25,
  TARGET_PICKER_BORDER_RADIUS: 15,
  WIDGET_WIDTH: 100,
  WIDGET_HEIGHT: 25,
  TAB_HEADER_HEIGHT: 25
};
CONSTANTS.WIDGET_EXTENT = pt(CONSTANTS.WIDGET_WIDTH, CONSTANTS.WIDGET_HEIGHT);
