name: pull-request
on:
  pull_request:
    types: [ready_for_review, reopened]
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: delivery-much/actions-assigner@v1
        with:
          reviewers: frcroth,Paula-Kli,SilvanVerhoeven,linusha,T4rikA
